### PR TITLE
Prevent race condition which returned wrong error with nextTick

### PR DESCRIPTION
**Pull request by jacktuck**
At the moment because the event loop continues (for a short while) when thowAsException is called we are returning errors which are not necessarily the cause of any issues.

For example, if you try to connect to remit, and put a hostname which does not exist or can not be reached. The error should be that the connection failed, but instead the error is publishing to an undefined connection.

image

Image shows the error returned when connection to non-functioning rabbitmq server. The highlighted text is the initial error before this change and below it the correct error with the fix in place.

### CODE REVIEW

**Comment by jacktuck** [comment]
I can probably make a test to make sure it doesn't regress and to demonstrate a bit better what i mean?

**Comment by jacktuck** [comment]
I need to make sure this works in all places we throw as exception as it needs to be in an async context

**Comment by jpwilliams** [comment]
I'll test this myself in a mo, but I'm confused as to why making the function return a promise fixes the issue? Does that mean we also have to `await` the throw?

**Comment by jacktuck** [comment]
I'll commit a test here now and you should be able to see. gimme a mo

**Comment by jacktuck** [comment]
@jpwilliams Alrighty, the commit for testing is up. 

So try npm test with and without the change in throwAsException

**Comment by jpwilliams** [comment]
Gotchya. Definitely makes sense to be `await`ing it as it's only really supposed to be used to escape from Promise... uh... holes?

Awesome. This seems like a naughty bug to pick up on! 👍 Nice!

**Comment by jpwilliams** [comment]
All looks good. Really interesting catch.

Only other place I can see it used is in `Remit.js` when connecting but everything `await`s that before going any further so the throw there would reject the promise and the right error would be caught _somewhere_.

Nice.

**Pull request merged**
