### PR TITLE
Allow priority of 0 (falsy)

### PR DESCRIPTION
**Pull request by jacktuck**

### CODE REVIEW

**Comment by jpwilliams** [comment]
Nice! Looks good. My only worry is when setting the priority to be between 0 and 255. The RabbitMQ docs read: 

> Resource Usage Considerations
> 
> If priority queues are desired, we recommend using between 1 and 10. Currently using more priorities will consume more resources (Erlang processes).

That's the current reason for using only 10. Should we break that or stick to that recommendation?

**Comment by jacktuck** [comment]
Oh i guess i missed those parts of the docs.

I think i'd implement it as spec suggest and then maybe add a warning to the README. But as far as i can tell, the actual spec does not define a limit, the number just must fit in a byte?

**Comment by jpwilliams** [comment]
So use `0-10` or `0-255`? :D 

I think the resource usage issue comes when you define a queue as having an `x-max-priority` of `255` rather than just sending a message with a `priority` over `10`. Therefore whatever limit we use we have to stick to, but if we use one over `10` then it impacts all queues regardless of their use of priority.

**Comment by jacktuck** [comment]
Lets discuss this some more and i can make this PR atop v2 if need be.

#21

**Pull request closed without merging**
